"""Generate the Expr AoS ablation, changing storage and growth only.

Kernel algorithms and accessors come from the same source as the SoA build.
"""
import re
import sys
from pathlib import Path

source, target = map(Path, sys.argv[1:])
s = source.read_text()
fields = 'tag a b c d e hash nlbv flags next origin'.split()
export_decl = '  integer(int32), allocatable, private :: ' + ','.join('export_' + f + '(:)' for f in fields)
assert export_decl in s
s = s.replace(export_decl, '  type :: expr_node\n    integer(int32) :: ' +
              ','.join(f + '=0' for f in fields) + '\n  end type\n' +
              '  type(expr_node), allocatable, private :: export_slots(:)')
local_decl = '    integer(int32), allocatable :: ' + ','.join(f + '(:)' for f in fields)
assert local_decl in s
s = s.replace(local_decl, '    type(expr_node), allocatable :: slots(:)')
s = s.replace('allocated(self%tag)', 'allocated(self%slots)').replace('size(self%tag)', 'size(self%slots)')
for f in fields:
    move = f'    call move_alloc(self%{f},export_{f})\n'
    assert move in s
    s = s.replace(move, '    call move_alloc(self%slots,export_slots)\n' if f == fields[0] else '')
    s = re.sub(r'call grow\(self%' + f + r',pos\);?\s*', '', s)
    s = re.sub(r'\bself%' + f + r'\(([^()]*)\)', r'self%slots(\1)%' + f, s)
    s = re.sub(r'\bexport_' + f + r'\(([^()]*)\)', r'export_slots(\1)%' + f, s)
s = s.replace('    id=self%count+1; pos=id-self%export_count',
              '    id=self%count+1; pos=id-self%export_count\n    call grow_slots(self%slots,pos)')
grow = '''  subroutine grow_slots(slots,need)
    type(expr_node), allocatable, intent(inout) :: slots(:)
    integer, intent(in) :: need
    type(expr_node), allocatable :: next_slots(:)
    integer :: cap,old,ios
    old=0
    if (allocated(slots)) old=size(slots)
    if (need<=old) return
    cap=max(16,old)
    do while(cap<need)
      if (cap>shiftr(huge(cap),1)) error stop kernel_error
      cap=cap*2
    end do
    allocate(next_slots(cap),stat=ios)
    if (ios/=0) error stop kernel_error
    if (old>0) next_slots(:old)=slots
    call move_alloc(next_slots,slots)
  end subroutine
'''
s = s.replace('contains\n  integer function scratch_capacity', 'contains\n' + grow + '  integer function scratch_capacity')
assert 'subroutine grow_slots' in s
s = '! Generated by scripts/make_expr_aos.py; edit src/expr.f90.\n' + s
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(s)
